### ISSUE TITLE
NPE on non-Yammer SignalFlow example on HEAD + JDK11

### ISSUE THREAD

**Issue by cory-signalfx** [signalfx/signalfx-java#68]
Getting this from HEAD:

```
Exception in thread "main" com.signalfx.signalflow.SignalFlowException: failed to send message for channel channel-KW3PKDAD
    at com.signalfx.signalflow.WebSocketTransport$TransportConnection.sendMessage(WebSocketTransport.java:525)
    at com.signalfx.signalflow.WebSocketTransport.execute(WebSocketTransport.java:122)
    at com.signalfx.signalflow.Computation.execute(Computation.java:185)
    at com.signalfx.signalflow.Computation.<init>(Computation.java:67)
    at com.signalfx.signalflow.SignalFlowClient.execute(SignalFlowClient.java:53)
    at com.signalfx.jvmtoy.App.main(App.java:19)
Caused by: java.lang.NullPointerException
    at com.signalfx.signalflow.WebSocketTransport$TransportConnection.sendMessage(WebSocketTransport.java:522)
    ... 5 more
```

Seems to be something related to @mpetazzoni's upgrade of Jetty [in here](https://github.com/signalfx/signalfx-java/commit/6c708b3285a286cd037853c90cba9e269157ac5f#diff-6fec74a7a5b433a57a7da3cb8d50c867R522).

```
$ java -version
java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)
```

**Comment by rmfitzpatrick** [comment]
fwiw I'm not running into this when building from head and using openjdk:
```
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

**Comment by mpetazzoni** [comment]
This has been fixed in the latest commits to `master`.
