### ISSUE TITLE
java.lang.NoClassDefFoundError: com/codahale/metrics/ThreadLocalRandomProxy updating resetting timer

### ISSUE THREAD

**Issue by finci-square** [signalfx/signalfx-java#98]
Attempting to use a resetting timer from https://github.com/signalfx/signalfx-java is yielding a ClassNotFoundException:
```
java.lang.ClassNotFoundException: com.codahale.metrics.ThreadLocalRandomProxy
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[na:na]
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
    at com.codahale.metrics.ResettingExponentiallyDecayingReservoir.update(ResettingExponentiallyDecayingReservoir.java:104) ~[signalfx-codahale-1.0.5.jar:4.1.12.1]
    at com.codahale.metrics.ResettingExponentiallyDecayingReservoir.update(ResettingExponentiallyDecayingReservoir.java:89) ~[signalfx-codahale-1.0.5.jar:4.1.12.1]
    at com.codahale.metrics.Histogram.update(Histogram.java:41) ~[metrics-core-4.1.12.1.jar:4.1.12.1]
    at com.codahale.metrics.Timer.update(Timer.java:199) ~[metrics-core-4.1.12.1.jar:4.1.12.1]
    at com.codahale.metrics.Timer.update(Timer.java:94) ~[metrics-core-4.1.12.1.jar:4.1.12.1]
```
Pom contains:
```
<dependency>
      <groupId>com.signalfx.public</groupId>
      <artifactId>signalfx-codahale</artifactId>
      <version>1.0.5</version>
    </dependency>
```
I'm unable to find `ThreadLocalRandomProxy` in https://github.com/dropwizard/dropwizard or anywhere else, any hints?

**Comment by mpetazzoni** [comment]
Fixed by https://github.com/signalfx/signalfx-java/commit/82062c16b9f5d61e0c4db6631778d5b5fe3e73b9 and released as part of version 1.0.8.
